### ISSUE TITLE
[FEAT] PlanDetail 뷰 개선작업

### ISSUE THREAD

**Issue by i-colours-u** [TeamBeMyPlan/BeMyPlan-iOS#113]
## 📌  Feature Issue
PlanDetail 뷰를 개선합니다...

## 📝  To-do
▶️ 
- [x] PlanDetail MVVM으로 전환하기
- [x] PlanDetail에서 스크롤 할 때 지도에서 말풍선 pop하도록 처리
- [x] 지도상에서 사소한 레이아웃 잡기
- [x] 네이버 지도 alert 손보기
- [x] 터치 영역도 같이 보기
