### ISSUE TITLE
Firebase Analytics 이벤트 로깅 추가

### ISSUE THREAD

**Issue by i-colours-u** [TeamBeMyPlan/BeMyPlan-iOS#117]
## 📌  Feature Issue
Firebase Analytics 이벤트 로그를 수집하도록 처리합니다.

## 📝  To-do
▶️ AppLog Manager 싱글턴 클래스 만들어서 처리하기
- [x] 노션보고 이벤트 case 정의하기
- [x] 각 액션별로 이벤트 처리하기
- [x] Singleton 에서 멀티스레드에 안전하도록 처리하기
