### ISSUE TITLE
[refactor] MyPlanPreview 아키텍처 개선

### ISSUE THREAD

**Issue by i-colours-u** [TeamBeMyPlan/BeMyPlan-iOS#124]
## 📌  Fix Issue
MyPlan 미리보기 화면에 대해 리팩토링을 진행합니다.

## 📝  To-do
- [ ] 기존 ViewModel을 Input Output 모델링을 명확히 하도록 수정합니다
- [ ] RxSwift를 도입해 코드를 어느정도 간결화하도록 처리합니다.
- [ ] 각 클래스별로 책임과 레이어를 확실히 구분합니다.
