### ISSUE TITLE
[feat] 마이플랜 부분 서버 연결

### ISSUE THREAD

**Issue by i-colours-u** [TeamBeMyPlan/BeMyPlan-iOS#137]
## 📌  Feature Issue
마이 플랜부분 서버 연결하기

## 📝  To-do
- [ ] 구매한 여행 일정 목록 들고오기
- [ ] 닉네임 정보 들고오기
- [ ] 구매한 여행 일정 없을 경우 추천 일정 띄우도록 처리
