### ISSUE TITLE
[Feat] Login 부분 Server 연결 - 현주

### ISSUE THREAD

**Issue by hellozo0** [TeamBeMyPlan/BeMyPlan-iOS#52]
## 📌  Feature Issue
Login Server 연결

## 📝  To-do
▶️ 로그인 서버 연결
- [ ] 서버 파일 세팅 BaseAPI, Service파일
- [ ] 소셜 로그인 서버 연결
- [ ] 소셜 로그인 후 닉네임 중복 체크 여부
