### ISSUE TITLE
[fix] 부족한 GUI,서버 채워넣기

### ISSUE THREAD

**Issue by i-colours-u** [TeamBeMyPlan/BeMyPlan-iOS#59]
## 📌  Fix Issue
테스트 플라이트 갱신을 위해 필요한 서버,GUI 를 채워넣습니다.
## 📝  To-do
- [ ] 토스트 메세지 완성하기
- [x] 업로드 신청 완성하기
- [ ] 복사 기능 만들기
