### ISSUE TITLE
[chore] GITHUB 레포 슬랙연동하기

### ISSUE THREAD

**Issue by i-colours-u** [TeamBeMyPlan/BeMyPlan-iOS#8]
## 📌  Feature Issue
슬랙 연동해두기 ^_^

## 📝  To-do
▶️
- [x] PR 날릴때 Alarm 전송하기
- [x] Issue 생성될 때 Alarm 전송하기
- [x] 머지 될 때 Alarm 전송하기
