### ISSUE TITLE
[feat] SignUP nickName 중복여부 - server

### ISSUE THREAD

**Issue by hellozo0** [TeamBeMyPlan/BeMyPlan-iOS#92]
## 📌  Feature Issue
SignUP nickName 중복여부 - server

## 📝  To-do
▶️ 파일 세팅
- [ ] 서버 파일 세팅
- [ ] 중복여부 오류창
- [ ] 중복 되면 버튼 비활성화 
- [ ]  완료되면 회원가입 되도록
